### ISSUE TITLE
Website frontend

### ISSUE THREAD

**Issue by albertgong1** [xforeverjlx/arxiv_website#2]
**Todos for Johann:**
- [x] Changing moderator identifier to be name-category (since some moderators belong to multiple queues)
- [x] Display this information at the bottom of the page (in a much smaller font)
- [x] Pull queues by name-category (note: currently it's being pulled by category)

**Todos for Steve:**
- [x] Add functionality to retrieve and display the title, the authors, any meta-data comment, and the abstract. Clicking on the "Article" button downloads the PDF. For reference, this is what the current moderation page looks like:
![image (10)](https://github.com/user-attachments/assets/f0135ec0-d50e-4afb-b2f9-c02a11bb8571)

**Other todos:**
- [X] Implement "Submit button" (same as "Save and edit next submission")
- [ ] Clarify with Tom that it suffices to choose another category and select "Start Moderation". Or implement a "Change category" button (for moderators that belong to multiple categories).

**Comment by albertgong1** [comment]
- Do we want a back button? (note: just using the browser back button wouldn't work because the firestore gets updated after you submit)

**Comment by lee-johann** [comment]
- [x] Update option wording to Tom's new guidelines
- [x] Change secondary decision to only show if "Bad fit" is selected for primary
- [x] Progress bar
- [x] Stylistic changes: bold "authors", "abstract",  hide paper ID and replace it with paper title
